class Database {
  users = [
    {
      id: 1,
      firstname: 'Silvia',
      lastname: 'Montero',
      gender: 'female',
      email: 'silvia.montero@example.com',
      address: {
        street: '4652 Calle de Bravo Murillo',
        city: 'Logroño',
        country: 'Spain',
      },
      phone: '991-889-476',
      cell: '632-435-513',
    },
    {
      id: 2,
      firstname: 'Roope',
      lastname: 'Kyllo',
      gender: 'male',
      email: 'roope.kyllo@example.com',
      address: {
        street: '5016 Rautatienkatu',
        city: 'Kaustinen',
        country: 'Finland',
      },
      phone: '05-211-916',
      cell: '042-863-01-02',
    },
    {
      id: 3,
      firstname: 'Giliam',
      lastname: 'Nagtegaal',
      gender: 'male',
      email: 'giliam.nagtegaal@example.com',
      address: {
        street: '5118 Hoogaarshof',
        city: 'Rietmolen',
        country: 'Netherlands',
      },
      phone: '(0197) 898491',
      cell: '(06) 19971471',
    },
    {
      id: 4,
      firstname: 'Gentil',
      lastname: 'da Mota',
      gender: 'male',
      email: 'gentil.damota@example.com',
      address: {
        street: '2586 Rua Duque de Caxias ',
        city: 'Várzea Paulista',
        country: 'Brazil',
      },
      phone: '(90) 2772-8657',
      cell: '(40) 5385-7389',
    },
    {
      id: 5,
      firstname: 'Arlene',
      lastname: 'da Conceição',
      gender: 'female',
      email: 'arlene.daconceicao@example.com',
      address: {
        street: '4485 Travessa dos Martírios',
        city: 'Vitória de Santo Antão',
        country: 'Brazil',
      },
      phone: '(64) 2966-6854',
      cell: '(27) 7122-2692',
    },
    {
      id: 6,
      firstname: 'Timofiy',
      lastname: 'Aliksiychuk',
      gender: 'male',
      email: 'timofiy.aliksiychuk@example.com',
      address: {
        street: '7168 Mikeshina',
        city: 'Yani Kapu',
        country: 'Ukraine',
      },
      phone: '(096) U65-5551',
      cell: '(097) I99-5713',
    },
    {
      id: 7,
      firstname: 'Ryder',
      lastname: 'Williams',
      gender: 'male',
      email: 'ryder.williams@example.com',
      address: {
        street: '1530 Tecumseh Rd',
        city: 'Shelbourne',
        country: 'Canada',
      },
      phone: 'K19 C79-4697',
      cell: 'C32 P65-6311',
    },
    {
      id: 8,
      firstname: 'Archie',
      lastname: 'Wright',
      gender: 'male',
      email: 'archie.wright@example.com',
      address: {
        street: '9084 Grey Street',
        city: 'Whangarei',
        country: 'New Zealand',
      },
      phone: '(946)-814-9646',
      cell: '(595)-586-1771',
    },
    {
      id: 9,
      firstname: 'Randy',
      lastname: 'Byrd',
      gender: 'male',
      email: 'randy.byrd@example.com',
      address: {
        street: '8690 Pockrus Page Rd',
        city: 'Oakland',
        country: 'United States',
      },
      phone: '(872) 744-1834',
      cell: '(426) 248-1392',
    },
    {
      id: 10,
      firstname: 'Neel',
      lastname: 'Shukla',
      gender: 'male',
      email: 'neel.shukla@example.com',
      address: {
        street: '2268 Hazratganj',
        city: 'Davanagere',
        country: 'India',
      },
      phone: '9575642189',
      cell: '7776755844',
    },
    {
      id: 11,
      firstname: 'Rúdi',
      lastname: 'Alves',
      gender: 'male',
      email: 'rudi.alves@example.com',
      address: {
        street: '9494 Rua São José ',
        city: 'Maringá',
        country: 'Brazil',
      },
      phone: '(27) 3940-5598',
      cell: '(97) 1474-0547',
    },
    {
      id: 12,
      firstname: 'Aada',
      lastname: 'Aho',
      gender: 'female',
      email: 'aada.aho@example.com',
      address: { street: '2132 Visiokatu', city: 'Sund', country: 'Finland' },
      phone: '02-895-840',
      cell: '047-731-16-75',
    },
    {
      id: 13,
      firstname: 'Sophia',
      lastname: 'Palmer',
      gender: 'female',
      email: 'sophia.palmer@example.com',
      address: {
        street: '5455 North Road',
        city: 'Passage West',
        country: 'Ireland',
      },
      phone: '041-577-4464',
      cell: '081-636-6448',
    },
    {
      id: 14,
      firstname: 'Elsa',
      lastname: 'Almonte',
      gender: 'female',
      email: 'elsa.almonte@example.com',
      address: {
        street: '8405 Diagonal Chile',
        city: 'San Juan de Guadalupe',
        country: 'Mexico',
      },
      phone: '(616) 031 0548',
      cell: '(693) 253 7393',
    },
    {
      id: 15,
      firstname: 'Noelle',
      lastname: 'Butler',
      gender: 'female',
      email: 'noelle.butler@example.com',
      address: {
        street: '4263 Marsh Ln',
        city: 'Warrnambool',
        country: 'Australia',
      },
      phone: '03-8418-4070',
      cell: '0488-666-134',
    },
    {
      id: 16,
      firstname: 'Charlie',
      lastname: 'Hubert',
      gender: 'male',
      email: 'charlie.hubert@example.com',
      address: {
        street: '4189 Montée du Chemin-Neuf',
        city: 'Nanterre',
        country: 'France',
      },
      phone: '03-79-41-71-83',
      cell: '06-10-98-68-52',
    },
    {
      id: 17,
      firstname: 'Alis a',
      lastname: 'Lauri',
      gender: 'female',
      email: 'alisa.lauri@example.com',
      address: {
        street: '5607 Reijolankatu',
        city: 'Kuusamo',
        country: 'Finland',
      },
      phone: '03-735-668',
      cell: '045-831-39-01',
    },
    {
      id: 18,
      firstname: 'Toivo',
      lastname: 'Leppanen',
      gender: 'male',
      email: 'toivo.leppanen@example.com',
      address: {
        street: '5480 Pyynikintie',
        city: 'Siikainen',
        country: 'Finland',
      },
      phone: '05-086-901',
      cell: '047-396-20-00',
    },
    {
      id: 19,
      firstname: 'Sophie',
      lastname: 'Grant',
      gender: 'female',
      email: 'sophie.grant@example.com',
      address: {
        street: '1170 Hillcrest Rd',
        city: 'Irving',
        country: 'United States',
      },
      phone: '(600) 700-0947',
      cell: '(961) 865-3009',
    },
    {
      id: 20,
      firstname: 'Mike',
      lastname: 'Burg',
      gender: 'male',
      email: 'mike.burg@example.com',
      address: {
        street: '6103 Berkelstraat',
        city: 'Ma rienvelde',
        country: 'Netherlands',
      },
      phone: '(0117) 930506',
      cell: '(06) 98152811',
    },
    {
      id: 21,
      firstname: 'Mieke',
      lastname: 'Maes',
      gender: 'female',
      email: 'mieke.maes@example.com',
      address: {
        street: '5399 Geesbergen',
        city: 'Ulsda',
        country: 'Netherlands',
      },
      phone: '(0839) 449089',
      cell: '(06) 81315193',
    },
    {
      id: 22,
      firstname: 'Slavica',
      lastname: 'Mišković',
      gender: 'female',
      email: 'slavica.miskovic@example.com',
      address: { street: '9276 Klinska', city: 'Bujanovac', country: 'Serbia' },
      phone: '024-3988-787',
      cell: '061-6418-472',
    },
    {
      id: 23,
      firstname: 'Tara',
      lastname: 'Eira',
      gender: 'female',
      email: 'tara.eira@example.com',
      address: {
        street: '4846 Åkebergveien',
        city: 'Mandal',
        country: 'Norway',
      },
      phone: '78011966',
      cell: '95510429',
    },
    {
      id: 24,
      firstname: 'مهدیس',
      lastname: 'زارعی',
      gender: 'female ',
      email: 'mhdys.zraay@example.com',
      address: { street: '9889 پارک ولیعصر', city: 'شیراز', country: 'Iran' },
      phone: '093-87189087',
      cell: '0962-634-5110',
    },
    {
      id: 25,
      firstname: 'Paul',
      lastname: 'Solheim',
      gender: 'male',
      email: 'paul.solheim@example.com',
      address: { street: '8252 Hansegata', city: 'Håkvik', country: 'Norway' },
      phone: '58882446',
      cell: '42804879',
    },
    {
      id: 26,
      firstname: 'Victor',
      lastname: 'Miller',
      gender: 'male',
      email: 'victor.miller@example.com',
      address: {
        street: '7287 Dufferin St',
        city: 'Trout Lake',
        country: 'Canada',
      },
      phone: 'B92 T94-1644',
      cell: 'M96 I94-6630',
    },
    {
      id: 27,
      firstname: 'Pooja',
      lastname: 'Nagane',
      gender: 'female',
      email: 'pooja.nagane@example.com',
      address: {
        street: '4529 Carter Rd Promenade',
        city: 'Panvel',
        country: 'India',
      },
      phone: '9394403256',
      cell: '8657117387',
    },
    {
      id: 28,
      firstname: 'Silje',
      lastname: 'Møller',
      gender: 'female',
      email: 'silje.moller@example.com',
      address: { street: '3494 Lysalleen', city: 'Beder', country: 'Denmark' },
      phone: '96534834',
      cell: '27439329',
    },
    {
      id: 29,
      firstname: 'Leanne',
      lastname: 'Clark',
      gender: 'female',
      email: 'leanne.clark@example.com',
      address: { street: '1987 Grand Ave', city: 'Jasper', country: 'Canada' },
      phone: 'V62 J63-1664',
      cell: 'X16 V05-6575',
    },
    {
      id: 30,
      firstname: 'Cihangir',
      lastname: 'Brekelmans',
      gender: 'male',
      email: 'cihangir.breke lmans@example.com',
      address: {
        street: '1842 De Dagmaat',
        city: 'Ruischerbrug',
        country: 'Netherlands',
      },
      phone: '(095) 9946767',
      cell: '(06) 02965956',
    },
    {
      id: 31,
      firstname: 'Amelia',
      lastname: 'Scott',
      gender: 'female',
      email: 'amelia.scott@example.com',
      address: { street: '5036 King St', city: 'Belmont', country: 'Canada' },
      phone: 'A54 U75-2705',
      cell: 'F01 G37-2353',
    },
    {
      id: 32,
      firstname: 'Paraskeva',
      lastname: 'Marchuk',
      gender: 'female',
      email: 'paraskeva.marchuk@example.com',
      address: {
        street: '9259 Viyskova',
        city: 'Reshetil ivka',
        country: 'Ukraine',
      },
      phone: '(068) B10-5196',
      cell: '(099) T98-0268',
    },
    {
      id: 33,
      firstname: 'Justine',
      lastname: 'Leroy',
      gender: 'female',
      email: 'justine.leroy@example.com',
      address: {
        street: '1172 Avenue de la République',
        city: 'Asnières-sur-Seine',
        country: 'France',
      },
      phone: '03-64-37-54-45',
      cell: '06-95-75-36-29',
    },
    {
      id: 34,
      firstname: 'Addison',
      lastname: 'Anderson',
      gender: 'female',
      email: 'addison.anderson@example.com',
      address: {
        street: '5640 Dominion Road',
        city: 'Nelson',
        country: 'New Zealand',
      },
      phone: '(062) -211-0003',
      cell: '(593)-774-3655',
    },
    {
      id: 35,
      firstname: 'Anjo',
      lastname: 'Croes',
      gender: 'female',
      email: 'anjo.croes@example.com',
      address: {
        street: '8415 Beverwijkerstraatweg',
        city: 'Gaast',
        country: 'Netherlands',
      },
      phone: '(006) 8812205',
      cell: '(06) 07581827',
    },
    {
      id: 36,
      firstname: 'Kaya',
      lastname: 'Ertürk',
      gender: 'male',
      email: 'kaya.erturk@example.com',
      address: {
        street: '4836 Necatibey Cd',
        city: 'Yalova',
        country: 'Turkey',
      },
      phone: '(856)-079-0531',
      cell: '(698)-752-4028',
    },
    {
      id: 37,
      firstname: 'Patricia',
      lastname: 'Orosco ',
      gender: 'female',
      email: 'patricia.orosco@example.com',
      address: {
        street: '3193 Cerrada Sur Valverde',
        city: 'El Pueblito',
        country: 'Mexico',
      },
      phone: '(661) 873 1123',
      cell: '(692) 734 0889',
    },
    {
      id: 38,
      firstname: 'Johan',
      lastname: 'Sørensen',
      gender: 'male',
      email: 'johan.sorensen@example.com',
      address: {
        street: '3570 Tjørnevej',
        city: 'Juelsminde',
        country: 'Denmark',
      },
      phone: '48827582',
      cell: '94713427',
    },
    {
      id: 39,
      firstname: 'Tereza',
      lastname: 'Romenskiy',
      gender: 'female',
      email: 'tereza.romenskiy@example.com',
      address: { street: '3804 Kioto', city: 'Smila', country: 'Ukraine' },
      phone: '(066) I33-5589',
      cell: '(097) Y26-6337',
    },
    {
      id: 40,
      firstname: 'Héctor',
      lastname: 'Mora',
      gender: 'male',
      email: 'hector.mora@example.com',
      address: {
        street: '3064 Calle de La Almudena',
        city: 'Gijó n',
        country: 'Spain',
      },
      phone: '946-168-622',
      cell: '654-670-308',
    },
    {
      id: 41,
      firstname: 'Slavobor',
      lastname: 'Franchuk',
      gender: 'male',
      email: 'slavobor.franchuk@example.com',
      address: {
        street: '9089 Rostovska',
        city: 'Bershad',
        country: 'Ukraine',
      },
      phone: '(098) V7 3-9360',
      cell: '(066) K03-7869',
    },
    {
      id: 42,
      firstname: 'Marcus',
      lastname: 'Nielsen',
      gender: 'male',
      email: 'marcus.nielsen@example.com',
      address: {
        street: '3913 Solvej',
        city: 'Fredeikssund',
        country: 'Denmark',
      },
      phone: '78868393',
      cell: '78062844',
    },
    {
      id: 43,
      firstname: 'Ch arlotte',
      lastname: 'Leclerc',
      gender: 'female',
      email: 'charlotte.leclerc@example.com',
      address: {
        street: "7437 Rue de L'Église",
        city: 'Angers',
        country: 'France',
      },
      phone: '05-68-72-99-09',
      cell: '06-52-45-75-86',
    },
    {
      id: 44,
      firstname: 'Yuhimiya',
      lastname: 'Bolyuh',
      gender: 'female',
      email: 'yuhimiya.bolyuh@example.com',
      address: {
        street: '1071 Antonovicha',
        city: 'Chernivci',
        country: 'Ukraine',
      },
      phone: '(098) Y55-5087',
      cell: '(099) E84-2384',
    },
    {
      id: 45,
      firstname: 'Urban',
      lastname: 'Garcia',
      gender: 'male',
      email: 'urban.ga rcia@example.com',
      address: {
        street: '5767 Rue Denfert-Rochereau',
        city: 'Villars-Sous-Yens',
        country: 'Switzerland',
      },
      phone: '077 384 62 48',
      cell: '076 173 31 11',
    },
    {
      id: 46,
      firstname: 'Ralf',
      lastname: 'Mathieu',
      gender: 'male',
      email: 'ralf.mathieu@example.com',
      address: {
        street: '1360 Rue Abel-Gance',
        city: 'Les Enfers',
        country: 'Switzerland',
      },
      phone: '076 093 14 40',
      cell: '076 577 54 62',
    },
    {
      id: 47,
      firstname: 'Cristian',
      lastname: 'Duran',
      gender: 'male',
      email: 'cristian.duran@example.com',
      address: {
        street: '4213 Aven ida del Planetario',
        city: 'Orense',
        country: 'Spain',
      },
      phone: '938-774-902',
      cell: '681-620-419',
    },
    {
      id: 48,
      firstname: 'Wissam',
      lastname: 'Schoonenberg',
      gender: 'male',
      email: 'wissam.schoonenberg@example.com',
      address: {
        street: '5192 Creijtestraat',
        city: 'Kerkwe rve',
        country: 'Netherlands',
      },
      phone: '(0473) 803743',
      cell: '(06) 09877801',
    },
    {
      id: 49,
      firstname: 'Gitte',
      lastname: 'Weil',
      gender: 'female',
      email: 'gitte.weil@example.com',
      address: {
        street: '903 Kirchplatz',
        city: 'Waldmünchen',
        country: 'Germany',
      },
      phone: '0988-2673971',
      cell: '0176-6739599',
    },
    {
      id: 50,
      firstname: 'Sverre',
      lastname: 'Einvik',
      gender: 'male',
      email: 'sverre.einvik@example.com',
      address: {
        street: '2472 Kjelsåsløkka',
        city: 'Nesoddtangen',
        country: 'Norway',
      },
      phone: '83377455',
      cell: '42001698',
    },
  ];
}

module.exports = new Database();
